### ISSUE TITLE
Allow multiple affiliations for authors & translators

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice#951]
### Background

Currently the YAML frontmatter at the start of each narrative markdown file is parsed [by this code](https://github.com/nextstrain/auspice/blob/master/cli/server/parseNarrative.js#L23) into HTML to be rendered by the client as the fist page of the narrative. E.g. [this YAML](https://github.com/nextstrain/narratives/blob/master/ncov_sit-rep_2020-03-05.md) tuns into [this narrative page](https://nextstrain.org/narratives/ncov/sit-rep/2020-03-05).

Currently we display YAML fields `title`, `authors`, `authorLinks`, `affiliations`, `translators`, `translatorLinks`,  `date` and `updated`.

PR #937 created a function which allowed `authors`+`authorLinks` (or `translators`+`translatorLinks`) to be arrays. However `affiliations` must be a string and represents all authors.

### Changes requested

1. We should extend the functions created in #937 to allow parsing of multiple affiliations. I think the cleanest way to do this is to require that if the type is an array then it must be the same length as `authors`. Duplicate affiliations (which will be the norm) should be specified separately by the frontmatter and grouped together by the parsing code. They should receive superscript arabic numerals (as we currently do, but it's always `1`!). Empty elements in the array should be allowed for authors without an affiliation.

2. The key names should change to `authorAffiliations` and `translatorAffiliations`. For simplicity, they should be treated as independent objects for rendering purposes. For backwards compatibility, if `affiliations` is set it should be interpreted as `authorAffiliations`.

Note: It's possible for authors to have multiple affiliations. This would naturally be supported by nested arrays in YAML. This functionality isn't required for this issue, but could be part of it if you want!

@ncallaway would you be interested in this? (no problem if not)

**Comment by ncallaway** [comment]
@jameshadfield I'd be happy to take a look at this. I'm pretty busy Monday, but should be able to take a look at this on Tuesday.

**Comment by CameronDevine** [comment]
@jameshadfield 

What do you think of the format [JOSS](https://joss.theoj.org/) uses for it's authors and affiliations?

Below is an excerpt from the frontmatter of their example paper, documented [here](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography):

```yaml
  - name: Adrian M. Price-Whelan
    orcid: 0000-0003-0872-7098
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Author Without ORCID
    affiliation: 2
affiliations:
 - name: Lyman Spitzer, Jr. Fellow, Princeton University
   index: 1
 - name: Institution 2
   index: 2
```

**Comment by tsibley** [comment]
There's also the [pandoc-scholar format](https://pandoc-scholar.github.io/#flexible-metadata-authoring) as prior art.

**Comment by CameronDevine** [comment]
Below is an example of the pandoc-scholar format,

```yaml
author:
  - Jane Doe:
      institute:
        - fosg
        - fop
      email: jane.doe@example.com
      orcid: 0000-0000-0000-0000
      equal_contributor: "yes"
      correspondence: "yes"
  - John Q. Doe:
      institute: fosg
      equal_contributor: "yes"
  - Peder Ås:
      institute: fosg
  - Juan Pérez:
      institute: acme
      email: juan.perez@example.edu
      correspondence: "yes"
institute:
  - fosg:
      name: Formatting Open Science Group
      address: 23 Science Street, Eureka, Mississippi, USA
      phone: +1 (555) 423 1338
      email: '{firstname}.{lastname}\@fosg.example.com'
  - fop: Federation of Planets
  - acme:
      name: Acme Corporation
```
